export default {
  translate: (str, value) => str.replace(":atr", value),
  createdAt: "زمان ایجاد",
  updatedAt: "زمان بروزرسانی",
  settings: {
    content: "متن :atr",
    rule: "قوانین",
    about: "درباره",
  },
  message: {
    cancelRow: "کنسل کردید",
    success: "حذف با موفقیت انجام شد",
    loading: "در انتظار حذف شدن....",
    errorMessage: "درخواست توسط سرور رد داده شد",
  },
  menu: {
    rule: "قوانین",
    about: "درباره",
    dashbord: "داشبورد",
    dashboard: "داشبورد",
    account: "پروفایل",
    accounts: "کاربران",
    admins: "مدیران",
    categories: "دسته بندی",
    plans: "پلن ها",
    products: "محصولات",
    transactions: "تراکنش ها",
    success: "تراکنش موفق",
    factores: "فاکتور ها اخیر",
  },
  plan: {
    title: "نام",
    price: "قیمت",
    event: "نوع",
    duration: "طول عمر",
  },
  product: {
    title: "نام",
    amount: "قیمت",
    description: "توضیحات",
    category: "دسته بندی",
    tags: "تگ ها",
    file: "فایل ها",
  },
  user: {
    _id: "کد",
    name: "نام",
    username: "نام کاربری",
    status: "وضعیت",
    mobile: "موبایل",
    password: "رمز عبور",
    role: "دسترسی",
  },
};
